#!/bin/sh

#
# This script provides some 
#

. `dirname $0`/functions



    case "$1" in
        create)
            sh jbossCreateInstance $2
            exit $RETVAL
        ;;

        start)
            service $2 start
            exit $RETVAL
        ;;

        stop)
            service $2 stop
            exit $RETVAL
        ;;

        delete)
            sh jbossDeleteInstance $2
            exit $RETVAL
        ;;

        list)
            sh jbossListIntance
            exit $RETVAL
        ;;

        clean)
            sh jbossCleanInstance $2
            exit $RETVAL
        ;;

	adduser)
           sh jbossAddUserInstance $2 $3 $4
           exit $RETVAL
        ;;	

    esac
